import { t } from "i18next";

export const GPT_PROVIDERS: { [key: string]: any } = {
  enjoyai: {
    name: "EnjoyAI",
    models: [
      "gpt-3.5-turbo-0125",
      "gpt-3.5-turbo",
      "gpt-3.5-turbo-1106",
      "gpt-3.5-turbo-16k",
      "gpt-3.5-turbo-instruct",
      "gpt-4-turbo",
      "gpt-4-turbo-2024-04-09",
      "gpt-4-0125-preview",
      "gpt-4-turbo-preview",
      "gpt-4-1106-preview",
      "gpt-4-vision-preview",
      "gpt-4",
      "gpt-4-32k",
      "gpt-4-0613",
      "gpt-4-32k-0613",
    ],
    configurable: [
      "model",
      "roleDefinition",
      "temperature",
      "numberOfChoices",
      "maxTokens",
      "frequencyPenalty",
      "presencePenalty",
      "historyBufferSize",
      "tts",
    ],
    types: ["gpt", "tts"],
  },
  openai: {
    name: "OpenAI",
    description: t("youNeedToSetupApiKeyBeforeUsingOpenAI"),
    models: [
      "gpt-3.5-turbo-0125",
      "gpt-3.5-turbo",
      "gpt-3.5-turbo-1106",
      "gpt-3.5-turbo-16k",
      "gpt-3.5-turbo-instruct",
      "gpt-4-turbo",
      "gpt-4-turbo-2024-04-09",
      "gpt-4-0125-preview",
      "gpt-4-turbo-preview",
      "gpt-4-1106-preview",
      "gpt-4-vision-preview",
      "gpt-4",
      "gpt-4-32k",
      "gpt-4-0613",
      "gpt-4-32k-0613",
    ],
    configurable: [
      "model",
      "baseUrl",
      "roleDefinition",
      "temperature",
      "numberOfChoices",
      "maxTokens",
      "frequencyPenalty",
      "presencePenalty",
      "historyBufferSize",
      "tts",
    ],
    types: ["gpt", "tts"],
  },
  googleGenerativeAi: {
    name: "Google Generative AI",
    models: ["gemini-pro"],
    configurable: [
      "model",
      "roleDefinition",
      "temperature",
      "maxTokens",
      "historyBufferSize",
      "tts",
    ],
    types: ["gpt"],
  },
  ollama: {
    name: "Ollama",
    description: t("ensureYouHaveOllamaRunningLocallyAndHasAtLeastOneModel"),
    baseUrl: "http://localhost:11434",
    models: [],
    configurable: [
      "model",
      "baseUrl",
      "roleDefinition",
      "temperature",
      "maxTokens",
      "historyBufferSize",
      "frequencyPenalty",
      "presencePenalty",
      "tts",
    ],
    types: ["gpt"],
  },
};
