import { t } from "i18next";

export const GPT_PROVIDERS: { [key: string]: any } = {
  enjoyai: {
    name: "EnjoyAI",
    models: [
      "gpt-4o-mini",
      "gpt-4o",
      "chatgpt-4o-latest",
      "gpt-4-turbo",
      "gpt-4",
    ],
    configurable: [
      "model",
      "roleDefinition",
      "temperature",
      "numberOfChoices",
      "maxTokens",
      "frequencyPenalty",
      "presencePenalty",
      "historyBufferSize",
      "tts",
    ],
  },
  openai: {
    name: "OpenAI",
    description: t("youNeedToSetupApiKeyBeforeUsingOpenAI"),
    models: [
      "gpt-4o-mini",
      "gpt-4o",
      "chatgpt-4o-latest",
      "gpt-4-turbo",
      "gpt-4",
    ],
    configurable: [
      "model",
      "baseUrl",
      "roleDefinition",
      "temperature",
      "numberOfChoices",
      "maxTokens",
      "frequencyPenalty",
      "presencePenalty",
      "historyBufferSize",
      "tts",
    ],
  },
  ollama: {
    name: "Ollama",
    description: t("ensureYouHaveOllamaRunningLocallyAndHasAtLeastOneModel"),
    baseUrl: "http://localhost:11434",
    models: [],
    configurable: [
      "model",
      "baseUrl",
      "roleDefinition",
      "temperature",
      "maxTokens",
      "historyBufferSize",
      "frequencyPenalty",
      "presencePenalty",
      "tts",
    ],
  },
};
