import { t } from "i18next";

export const TTS_PROVIDERS: { [key: string]: any } = {
  enjoyai: {
    name: "EnjoyAI",
    models: ["openai/tts-1", "openai/tts-1-hd", "azure/speech"],
    voices: {
      openai: ["alloy", "echo", "fable", "onyx", "nova", "shimmer"],
      azure: {
        "en-US": [
          "Ava",
          "Andrew",
          "Emma",
          "Brian",
          "Jenny",
          "Guy",
          "Aria",
          "Davis",
          "Jane",
          "Jason",
          "Sara",
          "Tony",
          "Nancy",
          "Amber",
          "Ana",
          "Ashley",
          "Brandon",
          "Christopher",
          "Cora",
          "Elizabeth",
          "Eric",
          "Jacob",
          "Michelle",
          "Monica",
          "Roger",
          "Steffan",
          "AIGenerate1",
          "AIGenerate2",
        ],
        "en-GB": [
          "Sonia",
          "Ryan",
          "Libby",
          "Abbi",
          "Alfie",
          "Bella",
          "Elliot",
          "Ethan",
          "Hollie",
          "Maisie",
          "Noah",
          "Oliver",
          "Olivia",
          "Thomas",
        ],
        "es-ES": [
          "Elvira",
          "Alvaro",
          "Abril",
          "Arnau",
          "Dario",
          "Elias",
          "Estrella",
          "Irene",
          "Laia",
          "Lia",
          "Nil",
          "Saul",
          "Teo",
          "Triana",
          "Vera",
          "Ximena",
        ],
        "zh-CN": [
          "Xiaoxiao",
          "Yunxi",
          "Yunjian",
          "Xiaoyi",
          "Yunyang",
          "Xiaochen",
          "Xiaohan",
          "Xiaomeng",
          "Xiaomo",
          "Xiaoqiu",
          "Xiaorui",
          "Xiaoshuang",
          "Xiaoyan",
          "Xiaoyou",
          "Xiaozhen",
          "Yunfeng",
          "Yunhao",
          "Yunxia",
          "Yunye",
          "Yunze",
        ],
        "ja-JP": [
          "Nanami",
          "Keita",
          "Aoi",
          "Daichi",
          "Mayu",
          "Naoki",
          "Shiori",
        ],
        "ko-KR": [
          "SunHi",
          "InJoon",
          "BongJin",
          "GookMin",
          "JiMin",
          "SeoHyeon",
          "SoonBok",
          "YuJin",
          "Hyunsu",
        ],
        "it-IT": [
          "Elsa",
          "Isabella",
          "Diego",
          "Benigno",
          "Calimero",
          "Cataldo",
          "Fabiola",
          "Fiamma",
          "Gianni",
          "Imelda",
          "Irma",
          "Lisandro",
          "Palmira",
          "Pierina",
          "Rinaldo",
          "Giuseppe",
        ],
        "de-DE": [
          "Katja",
          "Conrad",
          "Amala",
          "Bernd",
          "Christoph",
          "Elke",
          "Gisela",
          "Kasper",
          "Killian",
          "Klarissa",
          "Klaus",
          "Louisa",
          "Maja",
          "Ralf",
          "Tanja",
        ],
        "fr-FR": [
          "Denise",
          "Henri",
          "Alain",
          "Brigitte",
          "Celeste",
          "Claude",
          "Coralie",
          "Eloise",
          "Jacqueline",
          "Jerome",
          "Josephine",
          "Maurice",
          "Yves",
          "Yvette",
        ],
      },
    },
    configurable: ["model", "voice"],
  },
  openai: {
    name: "OpenAI",
    description: t("youNeedToSetupApiKeyBeforeUsingOpenAI"),
    models: ["tts-1", "tts-1-hd"],
    voices: ["alloy", "echo", "fable", "onyx", "nova", "shimmer"],
    configurable: ["model", "voice", "baseUrl"],
  },
};
